name: hedgeMaze
version: "1.1-SNAPSHOT"
author: Grant Mills
main: millscraft.HedgeMaze
commands:
   hedgeMaze:
      description: Creates a hedge maze south and east of the given coordinates
      usage: /hedgeMaze
