name: hedgeMaze
version: "1.2-SNAPSHOT"
author: Grant Mills
main: HedgeMaze
commands:
   hedgeMaze:
      description: Creates a hedge maze south and east of the given coordinates
      usage: /hedgeMaze
